# Generated by Django 3.2.6 on 2021-08-30 22:20

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_auto_20210822_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=django_countries.fields.CountryField(default='NG', max_length=2),
        ),
    ]
