# Generated by Django 3.2.6 on 2021-09-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_auto_20210830_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
