# Generated by Django 3.2.6 on 2021-09-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_auto_20210902_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=200),
        ),
    ]
